---
- hosts: all
  become: true

  tasks:

    - name: remove apache2 package and php
      ansible.builtin.package:
        name: 
          - "{{ apache_package}}"
          - "{{ php_package}}"
        state: absent



    
    
    
    
    
    
